kind: Template
apiVersion: v1
metadata:
  name: ${NAME}
objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        description: Defines how to deploy a ubuntu container for benchmarking minio
      generation: 1
      name: "${NAME}"
      creationTimestamp: 
      labels:
        app: ${NAME}
    spec:
      containers:
        - env:
            - name: MINIO_ACCESS_KEY
              value: ${MINIO_ACCESS_KEY}
            - name: MINIO_SECRET_KEY
              value: ${MINIO_SECRET_KEY}
          image: '${IMAGESTREAM}'
          imagePullPolicy: Always
          name: ${NAME}
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command: ["./s3-benchmark"]
          args: ["-a", "${MINIO_ACCESS_KEY}", "-s", "${MINIO_SECRET_KEY}", "-u", "${MINIO_SERVER_ADDRESS}", "-z", "${MINIO_OBJECT_SIZE}"]
      restartPolicy: Never
      activeDeadlineSeconds: 900
      dnsPolicy: ClusterFirst
    status: {}
parameters:
- name: NAME
  displayName: Name to apply to objects in the template
  value: cap-minio-eagle-dev-benchmark
  required: true
- name: IMAGESTREAM
  displayName: ImageStream to deploy, built from buildconfig template
  value: registry/minio-benchmark:stable
  required: true
- name: MINIO_SERVER_ADDRESS
  displayName: Address of minio server
  value: https://minioserver.domain.com
  required: true
- name: MINIO_ACCESS_KEY
  displayName: Minio access key for accessing server to be benchmarked
  required: true
- name: MINIO_SECRET_KEY
  displayName: Minio secret key for accessing server to be benchmarked
  required: true
- name: MINIO_OBJECT_SIZE
  displayName: Object size to use for benchmarking. In bytes with postfix K, M, and G (default "1M")
  value: 1M
  required: true